In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")


In [2]:
# chisquares test
data=sns.load_dataset('tips')

In [3]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data[["sex","smoker"]]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [6]:
# summerisation of data using crosstab
data_table=pd.crosstab(data['sex'],data['smoker'])

In [7]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [8]:
observed_values=data_table.values

In [9]:
observed_values

array([[60, 97],
       [33, 54]])

In [12]:
import scipy.stats as stats
stats_test,p,dof,expected_values=stats.chi2_contingency(observed_values)

In [13]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
# using chisquare critical method
dof=1

In [15]:
from scipy.stats import chi2

In [16]:
for i in zip(observed_values,expected_values):
    print(i)

(array([60, 97]), array([59.84016393, 97.15983607]))
(array([33, 54]), array([33.15983607, 53.84016393]))


In [17]:
chisquare_test=sum([(o-e)**2/e for o,e in zip(observed_values,expected_values)])

In [18]:
chisquare_test

array([0.00119737, 0.00073745])

In [19]:
chisquare_stats=chisquare_test[0]+chisquare_test[1]

In [20]:
chisquare_stats

np.float64(0.001934818536627623)

In [21]:
dof

1

In [22]:
alpha=0.05

In [23]:
chi2_critical=chi2._ppf(1-alpha,dof)

In [24]:
chi2_critical

np.float64(3.841458820694124)

In [25]:
if chisquare_stats>=chi2_critical:
    print("Reject null hypothesis,there is a relationship between the categorical variables")
else:
    print("Fail to reject null hypothesis,no relationship")

Fail to reject null hypothesis,no relationship


In [26]:
# p value method
p_value=1-chi2.cdf(x=chisquare_stats,df=dof)

In [27]:
p_value

np.float64(0.964915107315732)

In [28]:
if p_value<0.05:
    print("Reject null hypothesis,there is a relationship between the categorical variables")
else:
    print("Fail to reject null hypothesis,no relationship")

Fail to reject null hypothesis,no relationship


In [33]:
# No of hours studied daily on a weekly basis
# modndey,tuesday.......sunday

expected_data=[8,5,6,7,4,5,3]
observed_data=[7,6,5,8,4,6,4]
sum(expected_data),sum(observed_data)

(38, 40)

In [37]:
chisqstats,pvalue=stats.chisquare(observed_values,expected_values)

In [38]:
# using critical approch
critical_value=stats.chi2.ppf(1-alpha,dof)

In [43]:
chisqstats=chisqstats[0]+chisqstats[1]

In [45]:
if chisqstats>=critical_value:
    print("Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis


In [46]:
# F test
# two workers >> if one is more efficient than other one
worker1=[45,50,55,60,65,70,75,80,85,90]
worker2=[30,35,40,45,50,55,60,65,70,75]


In [47]:
fstats=np.var(worker1)/np.var(worker2)

In [48]:
fstats

np.float64(1.0)

In [49]:
df1=len(worker1)-1
df2=len(worker2)-1

In [50]:
df1

9

In [51]:
df2

9

In [52]:
critical_value=stats.f.ppf(q=1-alpha,dfn=df1,dfd=df2)

In [53]:
if fstats>critical_value:
    print("Reject null hypothesis,worker1 is more efficient than worker2")
else:
    print("Fail to reject null hypothesis,worker1 is not more efficient than worker2")

Fail to reject null hypothesis,worker1 is not more efficient than worker2


In [ ]:
# ANOVA test>>compare of two or more than two samples
# An ANOVA test is used to determine whether there are any statistically significant differences between the means of three or more independent (unrelated) groups.
# The null hypothesis (H0) for ANOVA states that there are no differences among the group means, while the alternative hypothesis (H1) suggests that at least one group mean is different from the others.
